###
# GET http://localhost:9090/api/ordabl/all-users
GET http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/all-users


###

POST http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/user
Content-Type: 'application/json'

{
    "firstname": "Michael",
    "lastname": "Murdock",
    "email" : "purposedrive@chapel.com",
    "contact" : 1239999934,
    "school"  : "Stanford University College"

}
