###
GET http://localhost:9090/api/ordabl/all-users
# GET http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/all-users


# POST http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/user
###
POST http://localhost:8000/api/ordabl/user
Content-Type: 'application/json'

{
    "firstname": "Michael",
    "lastname": "Murdock",
    "email" : "purposr4ve@chapel.com",
    "contact" : 1239999934,
    "school"  : "Stanford University College"

}

###
POST http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/create-item
# POST http://localhost:8000/api/ordabl/create-item
Content-Type: 'application/json'

{
    "name" : "are u afraid"
}

###
GET http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/items

###
DELETE  http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/item/4



# POST http://kojoyeboah53i-d962a2da663c.herokuapp.com/api/ordabl/user
###
GET http://localhost:9090/api/ordabl/all-users

###
DELETE http://localhost:9090/api/ordabl/profile/7

